### ISSUE TITLE
Remove ext argument

### ISSUE THREAD

**Issue by frankenjoe** [audeering/audbackend#58]
As discussed in #49 we would like to remove the `ext` argument. The problem are existing Artifactory repositories that use a file structure where the path depends on the file extension, e.g.:

`.../folder/file/1.0.0/file-1.0.0.ext`

Instead we would like to switch to a format that is independent of the extension, e.g.:

`.../folder/1.0.0/file.ext`

Here's a possible receipt to support legacy repositories using `audb` as an example:

1. Rename repository and make it read-only, e.g. `data-legacy`
2. In the `audb` package we register a custom backend that can read the old file structure, e.g. `artifactory-legacy`
3. We add the legacy backend to the `~/.audb.yaml` configuration, e.g.:
    ```yaml
    ...
   repositories:
     ...
      - name: data-legacy
        backend: artifactory-legacy
        host: https://host.com
     ```
